package entitlement

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Cross-language test vectors.
//
// The gateway (TypeScript) builds the entitlement epoch; the validator (Go)
// verifies it. If their hashing disagrees by a single byte, every inclusion
// proof fails and the fee layer refuses every intent — a total outage that
// would look like a policy problem rather than an encoding bug.
//
// Rather than trust that two hand-written implementations agree, both sides
// test against ONE fixture generated here. A change to the encoding on either
// side breaks this file, which is the point.
//
// Regenerate with: go test ./pkg/entitlement -run TestWriteCrossLanguageVectors -update

var updateVectors = os.Getenv("UPDATE_VECTORS") != "" ||
	func() bool {
		for _, a := range os.Args {
			if a == "-update" || a == "--update" {
				return true
			}
		}
		return false
	}()

type vectorLeaf struct {
	Leaf         Leaf   `json:"leaf"`
	CanonicalHex string `json:"canonical_hex"`
	LeafHash     string `json:"leaf_hash"`
}

type vectorFile struct {
	Note     string       `json:"note"`
	Leaves   []vectorLeaf `json:"leaves"`
	SetHash  string       `json:"set_hash"`
	Root     string       `json:"root"`
	SetJSON  string       `json:"set_json"`
	Interior struct {
		Left   string `json:"left"`
		Right  string `json:"right"`
		Result string `json:"result"`
	} `json:"interior_hash_example"`
	HeaderSigningBytes struct {
		Header Header `json:"header"`
		Hex    string `json:"hex"`
	} `json:"header_signing_bytes"`
}

// vectorLeaves is the fixed input. Chosen to exercise the things that actually
// differ between languages: mixed case, an empty optional field, large integers
// beyond 32 bits, and ordering that is not the input order.
func vectorLeaves() []Leaf {
	return []Leaf{
		{ADIURL: "acc://zulu.acme/data", Status: StatusActive, Tier: "growth",
			IntentCeilingMicroUSD: 5_000_000, EpochCeilingMicroUSD: 100_000_000},
		{ADIURL: "acc://Alpha.ACME/data", Status: StatusActive, Tier: "",
			IntentCeilingMicroUSD: 1, EpochCeilingMicroUSD: 9_007_199_254_740_993},
		{ADIURL: "acc://mike.acme/data", Status: StatusSuspended, Tier: "starter",
			IntentCeilingMicroUSD: 0, EpochCeilingMicroUSD: 0},
	}
}

func TestWriteCrossLanguageVectors(t *testing.T) {
	if !updateVectors {
		t.Skip("set -update or UPDATE_VECTORS=1 to regenerate")
	}
	set := &Set{Leaves: vectorLeaves()}
	set.Normalize()

	var vf vectorFile
	vf.Note = "Generated by pkg/entitlement TestWriteCrossLanguageVectors. " +
		"The gateway publisher MUST reproduce every value here byte for byte."

	for _, l := range set.Leaves {
		h := l.Hash()
		vf.Leaves = append(vf.Leaves, vectorLeaf{
			Leaf:         l,
			CanonicalHex: hex.EncodeToString(l.Canonical()),
			LeafHash:     hex.EncodeToString(h[:]),
		})
	}
	sh, err := set.SetHash()
	if err != nil {
		t.Fatal(err)
	}
	vf.SetHash = sh
	vf.Root = set.Root()
	b, _ := json.Marshal(set.Leaves)
	vf.SetJSON = string(b)

	l0 := set.Leaves[0].Hash()
	l1 := set.Leaves[1].Hash()
	vf.Interior.Left = hex.EncodeToString(l0[:])
	vf.Interior.Right = hex.EncodeToString(l1[:])
	vf.Interior.Result = hex.EncodeToString(interiorHash(l0[:], l1[:]))

	hdr := Header{
		Epoch: 42, Root: vf.Root, SetHash: sh, PrevRoot: "",
		NativeUSDMicro: 3_141_592_653,
		IssuedAtUnix:   1800000000, NotAfterUnix: 1800003600,
		KeyID: "entitlement-2026-07",
	}
	vf.HeaderSigningBytes.Header = hdr
	vf.HeaderSigningBytes.Hex = hex.EncodeToString(hdr.SigningBytes())

	out, err := json.MarshalIndent(vf, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join("testdata", "entitlement_vectors.json")
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s", path)
}

// TestVectorsStillMatch guards the Go side against an accidental encoding
// change. If this fails, the wire format changed and every deployed validator
// disagrees with every published epoch.
func TestVectorsStillMatch(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "entitlement_vectors.json"))
	if err != nil {
		t.Skipf("no vectors yet: %v", err)
	}
	var want vectorFile
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatal(err)
	}

	set := &Set{Leaves: vectorLeaves()}
	set.Normalize()

	if got := set.Root(); got != want.Root {
		t.Errorf("root changed:\n got %s\nwant %s", got, want.Root)
	}
	gotSH, _ := set.SetHash()
	if gotSH != want.SetHash {
		t.Errorf("set hash changed:\n got %s\nwant %s", gotSH, want.SetHash)
	}
	if len(set.Leaves) != len(want.Leaves) {
		t.Fatalf("leaf count changed: got %d want %d", len(set.Leaves), len(want.Leaves))
	}
	for i, l := range set.Leaves {
		if got := hex.EncodeToString(l.Canonical()); got != want.Leaves[i].CanonicalHex {
			t.Errorf("leaf %d canonical encoding changed:\n got %s\nwant %s", i, got, want.Leaves[i].CanonicalHex)
		}
		h := l.Hash()
		if got := hex.EncodeToString(h[:]); got != want.Leaves[i].LeafHash {
			t.Errorf("leaf %d hash changed:\n got %s\nwant %s", i, got, want.Leaves[i].LeafHash)
		}
	}
	if got := hex.EncodeToString(want.HeaderSigningBytes.Header.SigningBytes()); got != want.HeaderSigningBytes.Hex {
		t.Errorf("header signing bytes changed:\n got %s\nwant %s", got, want.HeaderSigningBytes.Hex)
	}
}
