//go:build vectors

// Copyright 2026 Certen Protocol

// The cross-language vector writer, behind the vectors build tag (RB3-F83): it regenerates a file the
// gateway publisher must reproduce byte for byte, so it runs only when asked -
//
//	go test -tags vectors ./pkg/entitlement -run TestWriteCrossLanguageVectors
//
// TestVectorsStillMatch checks the committed vectors in every build.

package entitlement

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestWriteCrossLanguageVectors(t *testing.T) {
	set := &Set{Leaves: vectorLeaves()}
	set.Normalize()

	var vf vectorFile
	vf.Note = "Generated by pkg/entitlement TestWriteCrossLanguageVectors. " +
		"The gateway publisher MUST reproduce every value here byte for byte."

	for _, l := range set.Leaves {
		h := l.Hash()
		vf.Leaves = append(vf.Leaves, vectorLeaf{
			Leaf:         l,
			CanonicalHex: hex.EncodeToString(l.Canonical()),
			LeafHash:     hex.EncodeToString(h[:]),
		})
	}
	sh, err := set.SetHash()
	if err != nil {
		t.Fatal(err)
	}
	vf.SetHash = sh
	vf.Root = set.Root()
	b, _ := json.Marshal(set.Leaves)
	vf.SetJSON = string(b)

	l0 := set.Leaves[0].Hash()
	l1 := set.Leaves[1].Hash()
	vf.Interior.Left = hex.EncodeToString(l0[:])
	vf.Interior.Right = hex.EncodeToString(l1[:])
	vf.Interior.Result = hex.EncodeToString(interiorHash(l0[:], l1[:]))

	hdr := Header{
		Epoch: 42, Root: vf.Root, SetHash: sh, PrevRoot: "",
		NativeUSDMicro: 3_141_592_653,
		IssuedAtUnix:   1800000000, NotAfterUnix: 1800003600,
		KeyID: "entitlement-2026-07",
	}
	vf.HeaderSigningBytes.Header = hdr
	vf.HeaderSigningBytes.Hex = hex.EncodeToString(hdr.SigningBytes())

	out, err := json.MarshalIndent(vf, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join("testdata", "entitlement_vectors.json")
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s", path)
}
