# .golangci.yml
# golangci-lint configuration for Accumulate Lite Client

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
    - proofs_pending
  skip-dirs:
    - vendor
    - docs
    - testdata
    - proof/archive
  skip-files:
    - ".*_test.go"  # Skip test files with mock_disabled tag

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals  # We use some globals for configuration
    - godox             # Allow TODO/FIXME comments
    - lll               # Line length limit is too restrictive
    - wsl               # Whitespace linter is too strict

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/stretchr/testify/mock"
            desc: "Mock packages are not allowed. This codebase is mock-free."
          - pkg: "github.com/golang/mock"
            desc: "Mock packages are not allowed. This codebase is mock-free."
          - pkg: "go.uber.org/mock"
            desc: "Mock packages are not allowed. This codebase is mock-free."
          - pkg: "github.com/vektra/mockery"
            desc: "Mock packages are not allowed. This codebase is mock-free."

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    default-signifies-exhaustive: true

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: gitlab.com/accumulatenetwork/core/liteclient

  gosec:
    excludes:
      - G104  # Unhandled errors in deferred calls
      - G304  # File path provided as argument (needed for CLI tools)

  govet:
    check-shadowing: true

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude mock-related issues in files with mock_disabled build tag
    - path: ".*mock_disabled.*"
      linters:
        - depguard
    
    # Exclude test files from certain linters
    - path: "_test\\.go"
      linters:
        - dupl
        - gosec
        - goconst

    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Exclude vendor directory
    - path: "vendor/"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

  # Show all issues without truncation
  exclude-use-default: false

  # Don't skip issues in new code
  new: false