package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/certen/independant-validator/pkg/crypto/bls_zkp"
)

func main() {
	keysDir := "./bls_zk_keys_bls12381"
	if len(os.Args) > 1 {
		keysDir = os.Args[1]
	}

	pkPath := filepath.Join(keysDir, "proving_key.bin")
	vkPath := filepath.Join(keysDir, "verification_key.bin")
	csPath := filepath.Join(keysDir, "constraint_system.bin")

	prover := bls_zkp.NewBLS12381Prover()

	// Try to load existing keys
	if _, err := os.Stat(pkPath); err == nil {
		log.Printf("Loading existing BLS12-381 keys from %s...", keysDir)
		if err := prover.InitializeFromKeys(pkPath, vkPath, csPath); err != nil {
			log.Printf("Failed to load keys: %v, generating fresh keys...", err)
			if err := generateAndSaveKeys(prover, keysDir, pkPath, vkPath, csPath); err != nil {
				log.Fatalf("Failed to generate keys: %v", err)
			}
		}
	} else {
		log.Printf("No existing keys found, generating fresh BLS12-381 keys...")
		if err := generateAndSaveKeys(prover, keysDir, pkPath, vkPath, csPath); err != nil {
			log.Fatalf("Failed to generate keys: %v", err)
		}
	}

	// Export VK as hex strings for Tact contract
	vkExport, err := prover.ExportVerificationKeyHex()
	if err != nil {
		log.Fatalf("Failed to export VK: %v", err)
	}

	// Print Tact-compatible constants
	fmt.Println("// ═══════════════════════════════════════════════════════════════════════════════")
	fmt.Println("// BLS12-381 VERIFICATION KEY CONSTANTS FOR TACT CONTRACT")
	fmt.Println("// Generated by vk_converter_bls12381 tool")
	fmt.Println("// ═══════════════════════════════════════════════════════════════════════════════")
	fmt.Println()
	fmt.Printf("// Alpha (G1 compressed, 48 bytes)\n")
	fmt.Printf("inline fun vkAlpha(): Slice { return rawSlice(\"%s\"); }\n\n", vkExport.AlphaG1Hex)
	fmt.Printf("// Beta (G2 compressed, 96 bytes)\n")
	fmt.Printf("inline fun vkBeta(): Slice { return rawSlice(\"%s\"); }\n\n", vkExport.BetaG2Hex)
	fmt.Printf("// Gamma (G2 compressed, 96 bytes)\n")
	fmt.Printf("inline fun vkGamma(): Slice { return rawSlice(\"%s\"); }\n\n", vkExport.GammaG2Hex)
	fmt.Printf("// Delta (G2 compressed, 96 bytes)\n")
	fmt.Printf("inline fun vkDelta(): Slice { return rawSlice(\"%s\"); }\n\n", vkExport.DeltaG2Hex)

	for i, icHex := range vkExport.ICG1Hex {
		fmt.Printf("// IC[%d] (G1 compressed, 48 bytes)\n", i)
		fmt.Printf("inline fun vkIC%d(): Slice { return rawSlice(\"%s\"); }\n\n", i, icHex)
	}

	// Also output as JSON
	jsonBytes, _ := json.MarshalIndent(vkExport, "", "  ")
	jsonPath := filepath.Join(keysDir, "vk_tact.json")
	if err := os.WriteFile(jsonPath, jsonBytes, 0644); err != nil {
		log.Printf("Warning: could not write VK JSON: %v", err)
	} else {
		fmt.Fprintf(os.Stderr, "\nVK JSON also saved to: %s\n", jsonPath)
	}

	fmt.Fprintf(os.Stderr, "\nKeys directory: %s\n", keysDir)
	fmt.Fprintf(os.Stderr, "IC points: %d (4 public inputs + 1 base = 5 expected)\n", len(vkExport.ICG1Hex))
}

func generateAndSaveKeys(prover *bls_zkp.BLS12381Prover, keysDir, pkPath, vkPath, csPath string) error {
	if err := os.MkdirAll(keysDir, 0755); err != nil {
		return fmt.Errorf("create keys dir: %w", err)
	}

	log.Printf("Compiling SimpleBLSCircuit for BLS12-381 and running trusted setup...")
	if err := prover.Initialize(); err != nil {
		return fmt.Errorf("initialize prover: %w", err)
	}

	log.Printf("Saving keys to %s...", keysDir)
	if err := prover.SaveKeys(pkPath, vkPath, csPath); err != nil {
		return fmt.Errorf("save keys: %w", err)
	}

	log.Printf("Keys saved successfully")
	return nil
}
