/**
 * Deploy BLS ZK Verification Key to BLSZKVerifier Contract
 *
 * This script sets the Groth16 verification key on the BLSZKVerifier contract.
 * The verification key MUST match the proving key used by validators.
 *
 * Generated by bls-zk-setup tool.
 */

const { ethers } = require('ethers');

// Configuration
const OWNER_PRIVATE_KEY = '0xbf90cedf27a3009a2c8a1634971430e853872dc5d1dbb837e02beffa4760d9cf';
const RPC_URL = 'https://eth-sepolia.g.alchemy.com/v2/aosGJNJkUckm6lCldSEmP';
const BLS_ZK_VERIFIER_ADDRESS = '0x631B6444216b981561034655349F8a28962DcC5F';

// Verification key values (generated by bls-zk-setup)
const alpha1 = [
    "17692176761651478707031096954230700313913150008523989519811333171378179027243",
    "10600189104699477045238529897842866463452833177210035762343390229704017704490"
];

const beta2 = [
    ["7874892735347155965870087927817788292894715728597574705448460090348065068681", "21144494815167618011470863237718967383318467553461897982907948570780510689099"],
    ["8651410831090401804335615431324685214401640680949579558120406668182786495021", "1268711338096733335241946164265291216307311913874952402729340242797689662485"]
];

const gamma2 = [
    ["20080569808459769082224389979207691659228097272140328714534265357986177919577", "18177850420888715031009594060465959976406890675070806332276379524532651287576"],
    ["10212824501378593238733341872563220885966316205047995574825349341157618713571", "7557888565511338222477594632600490500138534242194822407495007385088671736811"]
];

const delta2 = [
    ["8453999845416756128269885240210766452928395228506505663808898845930999129301", "16523352591777564963202920178652816114819158559959879036971432722461810128879"],
    ["20277311262877503674395502056195998444536526442910000923546202370443304880757", "4555721364026350887077607128833856335815112251984624553071238865390659772514"]
];

// 5 IC points = 4 public inputs + 1
const ic_x = [
    "21685824402619168482027094894109770881505277307171198418040849667413348255412",
    "0",
    "13278410038919734129200914614141716561195456132020112113502116052645599374535",
    "11679023396031872746913642955277511801375264076098564031429716839881345660949",
    "615402441673649577494185586121091672240472118188094518512549031543506129726"
];

const ic_y = [
    "19506922410183101530162201786689964431642723953435739805894243936542471300770",
    "0",
    "19376736947543423613354300653774381449731843082077124582421483080301231343963",
    "4543413180507777310065933141084926038614028106623753274085046819808524370462",
    "20207737774075757176343821264752357210985670960579436107447617683498684408379"
];

// BLSZKVerifier ABI (only needed function)
const ABI = [
    'function setVerificationKey(uint256[2] calldata _alpha1, uint256[2][2] calldata _beta2, uint256[2][2] calldata _gamma2, uint256[2][2] calldata _delta2, uint256[] calldata _ic_x, uint256[] calldata _ic_y)',
    'function vkInitialized() view returns (bool)',
    'function owner() view returns (address)'
];

async function main() {
    console.log('='.repeat(70));
    console.log('Deploy BLS ZK Verification Key');
    console.log('='.repeat(70));
    console.log('');

    const provider = new ethers.JsonRpcProvider(RPC_URL);
    const wallet = new ethers.Wallet(OWNER_PRIVATE_KEY, provider);
    const contract = new ethers.Contract(BLS_ZK_VERIFIER_ADDRESS, ABI, wallet);

    console.log('Contract:', BLS_ZK_VERIFIER_ADDRESS);
    console.log('Signer:', wallet.address);

    // Check current state
    const vkInitialized = await contract.vkInitialized();
    console.log('VK Already Initialized:', vkInitialized);

    if (vkInitialized) {
        console.log('');
        console.log('WARNING: Verification key is already set.');
        console.log('Setting a new key will replace it.');
        console.log('');
    }

    // Check ownership
    try {
        const owner = await contract.owner();
        console.log('Contract Owner:', owner);
        if (wallet.address.toLowerCase() !== owner.toLowerCase()) {
            console.error('');
            console.error('ERROR: Signer is not the contract owner!');
            process.exit(1);
        }
    } catch (e) {
        console.log('Could not verify ownership (function may not exist)');
    }

    console.log('');
    console.log('Setting verification key...');
    console.log('  Alpha1:', alpha1[0].substring(0, 20) + '...');
    console.log('  IC points:', ic_x.length);

    try {
        const tx = await contract.setVerificationKey(
            alpha1,
            beta2,
            gamma2,
            delta2,
            ic_x,
            ic_y,
            { gasLimit: 500000n }
        );

        console.log('  TX:', tx.hash);
        const receipt = await tx.wait();
        console.log('  Block:', receipt.blockNumber);
        console.log('  Gas Used:', receipt.gasUsed.toString());
        console.log('');
        console.log('Verification key set successfully!');

        // Verify
        const newVkInitialized = await contract.vkInitialized();
        console.log('VK Initialized:', newVkInitialized);

    } catch (err) {
        console.error('Failed to set verification key:', err.message);
        process.exit(1);
    }

    console.log('');
    console.log('='.repeat(70));
    console.log('Done!');
    console.log('='.repeat(70));
}

main()
    .then(() => process.exit(0))
    .catch(error => {
        console.error('Fatal error:', error);
        process.exit(1);
    });
