/**
 * Update BLS ZK Verification Key on Contract
 * 
 * This updates the BLSZKVerifier contract with the local verification key
 * so that proofs generated by validators will verify correctly.
 */

const { ethers } = require('ethers');
const fs = require('fs');

// Configuration
const OWNER_PRIVATE_KEY = '0xbf90cedf27a3009a2c8a1634971430e853872dc5d1dbb837e02beffa4760d9cf';
const RPC_URL = 'https://eth-sepolia.g.alchemy.com/v2/aosGJNJkUckm6lCldSEmP';
const BLS_VERIFIER_ADDRESS = '0x631B6444216b981561034655349F8a28962DcC5F';

// Read raw JSON and parse with reviver to keep numbers as strings
const rawJSON = fs.readFileSync('../bls_zk_keys/verification_key.json', 'utf8');

// Custom JSON parser that keeps large numbers as strings
function parseBigIntJSON(json) {
  return JSON.parse(json, (key, value) => {
    // If it's a number that looks like it should be a BigInt, return as-is
    // The numeric values in the JSON will be parsed as numbers by default
    return value;
  });
}

// Actually, let's just read the deploy_vk.js which has the values as strings already
const deployScript = fs.readFileSync('../bls_zk_keys/deploy_vk.js', 'utf8');

// Extract values from the deploy script using regex
const alpha1Match = deployScript.match(/const alpha1 = \["(\d+)", "(\d+)"\]/);
const beta2Match = deployScript.match(/const beta2 = \[\["(\d+)", "(\d+)"\], \["(\d+)", "(\d+)"\]\]/);
const gamma2Match = deployScript.match(/const gamma2 = \[\["(\d+)", "(\d+)"\], \["(\d+)", "(\d+)"\]\]/);
const delta2Match = deployScript.match(/const delta2 = \[\["(\d+)", "(\d+)"\], \["(\d+)", "(\d+)"\]\]/);

// Extract IC arrays
const icXMatches = [...deployScript.matchAll(/"(\d+)"(?:,?\s*(?:\n|$))/gm)];
const icYSection = deployScript.match(/const ic_y = \[([\s\S]*?)\];/);

// Contract ABI
const ABI = [
  'function setVerificationKey(uint256[2] alpha1, uint256[2][2] beta2, uint256[2][2] gamma2, uint256[2][2] delta2, uint256[] ic_x, uint256[] ic_y)',
  'function vkInitialized() view returns (bool)',
  'function owner() view returns (address)'
];

async function main() {
  console.log('='.repeat(70));
  console.log('Update BLS ZK Verification Key');
  console.log('='.repeat(70));
  console.log('');
  
  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(OWNER_PRIVATE_KEY, provider);
  const contract = new ethers.Contract(BLS_VERIFIER_ADDRESS, ABI, wallet);
  
  console.log('Contract:', BLS_VERIFIER_ADDRESS);
  console.log('Signer:', wallet.address);
  console.log('');
  
  // Check owner
  const owner = await contract.owner();
  console.log('Contract owner:', owner);
  
  if (owner.toLowerCase() !== wallet.address.toLowerCase()) {
    console.log('ERROR: Signer is not the contract owner!');
    return;
  }
  
  // Values from deploy_vk.js (already as strings)
  const alpha1 = [
    "17692176761651478707031096954230700313913150008523989519811333171378179027243",
    "10600189104699477045238529897842866463452833177210035762343390229704017704490"
  ];
  
  const beta2 = [
    ["7874892735347155965870087927817788292894715728597574705448460090348065068681", "21144494815167618011470863237718967383318467553461897982907948570780510689099"],
    ["8651410831090401804335615431324685214401640680949579558120406668182786495021", "1268711338096733335241946164265291216307311913874952402729340242797689662485"]
  ];
  
  const gamma2 = [
    ["20080569808459769082224389979207691659228097272140328714534265357986177919577", "18177850420888715031009594060465959976406890675070806332276379524532651287576"],
    ["10212824501378593238733341872563220885966316205047995574825349341157618713571", "7557888565511338222477594632600490500138534242194822407495007385088671736811"]
  ];
  
  const delta2 = [
    ["8453999845416756128269885240210766452928395228506505663808898845930999129301", "16523352591777564963202920178652816114819158559959879036971432722461810128879"],
    ["20277311262877503674395502056195998444536526442910000923546202370443304880757", "4555721364026350887077607128833856335815112251984624553071238865390659772514"]
  ];
  
  const ic_x = [
    "21685824402619168482027094894109770881505277307171198418040849667413348255412",
    "0",
    "13278410038919734129200914614141716561195456132020112113502116052645599374535",
    "11679023396031872746913642955277511801375264076098564031429716839881345660949",
    "615402441673649577494185586121091672240472118188094518512549031543506129726"
  ];
  
  const ic_y = [
    "19506922410183101530162201786689964431642723953435739805894243936542471300770",
    "0",
    "19376736947543423613354300653774381449731843082077124582421483080301231343963",
    "4543413180507777310065933141084926038614028106623753274085046819808524370462",
    "20207737774075757176343821264752357210985670960579436107447617683498684408379"
  ];
  
  console.log('Setting verification key...');
  console.log('  Alpha1 X:', alpha1[0].substring(0, 20) + '...');
  console.log('  Alpha1 Y:', alpha1[1].substring(0, 20) + '...');
  console.log('  IC points:', ic_x.length);
  console.log('');
  
  try {
    const tx = await contract.setVerificationKey(
      alpha1, beta2, gamma2, delta2, ic_x, ic_y,
      { gasLimit: 500000n }
    );
    console.log('TX:', tx.hash);
    console.log('Waiting for confirmation...');
    
    const receipt = await tx.wait();
    console.log('Confirmed in block:', receipt.blockNumber);
    console.log('');
    
    // Verify
    const initialized = await contract.vkInitialized();
    console.log('VK Initialized:', initialized);
    
    // Read back to verify
    const slot0 = await provider.getStorage(BLS_VERIFIER_ADDRESS, 0);
    const storedAlpha1X = BigInt(slot0);
    const expectedAlpha1X = BigInt(alpha1[0]);
    
    if (storedAlpha1X === expectedAlpha1X) {
      console.log('');
      console.log('✓ SUCCESS: Verification key updated and verified!');
      console.log('  Proofs generated with local proving key should now verify.');
    } else {
      console.log('');
      console.log('Stored:', storedAlpha1X.toString());
      console.log('Expected:', expectedAlpha1X.toString());
      console.log('⚠ WARNING: VK may not have been set correctly');
    }
    
  } catch (err) {
    console.log('ERROR:', err.message);
    if (err.data) console.log('Data:', err.data);
  }
  
  console.log('');
  console.log('='.repeat(70));
  console.log('Done!');
  console.log('='.repeat(70));
}

main();
