/**
 * Update BLS ZK Verification Key on Contract
 * 
 * This updates the BLSZKVerifier contract with the local verification key
 * so that proofs generated by validators will verify correctly.
 */

const { ethers } = require('ethers');
const fs = require('fs');

// Configuration
const OWNER_PRIVATE_KEY = '0xbf90cedf27a3009a2c8a1634971430e853872dc5d1dbb837e02beffa4760d9cf';
const RPC_URL = 'https://eth-sepolia.g.alchemy.com/v2/aosGJNJkUckm6lCldSEmP';
const BLS_VERIFIER_ADDRESS = '0x631B6444216b981561034655349F8a28962DcC5F';

// Load local verification key
const localVK = JSON.parse(fs.readFileSync('../bls_zk_keys/verification_key.json', 'utf8'));

// Contract ABI
const ABI = [
  'function setVerificationKey(uint256[2] alpha1, uint256[2][2] beta2, uint256[2][2] gamma2, uint256[2][2] delta2, uint256[] ic_x, uint256[] ic_y)',
  'function vkInitialized() view returns (bool)',
  'function owner() view returns (address)'
];

async function main() {
  console.log('='.repeat(70));
  console.log('Update BLS ZK Verification Key');
  console.log('='.repeat(70));
  console.log('');
  
  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(OWNER_PRIVATE_KEY, provider);
  const contract = new ethers.Contract(BLS_VERIFIER_ADDRESS, ABI, wallet);
  
  console.log('Contract:', BLS_VERIFIER_ADDRESS);
  console.log('Signer:', wallet.address);
  console.log('');
  
  // Check owner
  const owner = await contract.owner();
  console.log('Contract owner:', owner);
  
  if (owner.toLowerCase() !== wallet.address.toLowerCase()) {
    console.log('ERROR: Signer is not the contract owner!');
    return;
  }
  
  // Convert verification key to contract format
  const alpha1 = [localVK.alpha1[0].toString(), localVK.alpha1[1].toString()];
  
  const beta2 = [
    [localVK.beta2[0][0].toString(), localVK.beta2[0][1].toString()],
    [localVK.beta2[1][0].toString(), localVK.beta2[1][1].toString()]
  ];
  
  const gamma2 = [
    [localVK.gamma2[0][0].toString(), localVK.gamma2[0][1].toString()],
    [localVK.gamma2[1][0].toString(), localVK.gamma2[1][1].toString()]
  ];
  
  const delta2 = [
    [localVK.delta2[0][0].toString(), localVK.delta2[0][1].toString()],
    [localVK.delta2[1][0].toString(), localVK.delta2[1][1].toString()]
  ];
  
  const ic_x = localVK.ic.map(ic => ic[0].toString());
  const ic_y = localVK.ic.map(ic => ic[1].toString());
  
  console.log('Setting verification key...');
  console.log('  Alpha1:', alpha1[0].substring(0, 20) + '...');
  console.log('  IC points:', ic_x.length);
  console.log('');
  
  try {
    const tx = await contract.setVerificationKey(
      alpha1, beta2, gamma2, delta2, ic_x, ic_y,
      { gasLimit: 500000n }
    );
    console.log('TX:', tx.hash);
    console.log('Waiting for confirmation...');
    
    const receipt = await tx.wait();
    console.log('Confirmed in block:', receipt.blockNumber);
    console.log('');
    
    // Verify
    const initialized = await contract.vkInitialized();
    console.log('VK Initialized:', initialized);
    
    // Read back to verify
    const slot0 = await provider.getStorage(BLS_VERIFIER_ADDRESS, 0);
    const storedAlpha1X = BigInt(slot0);
    const localAlpha1X = BigInt(localVK.alpha1[0]);
    
    if (storedAlpha1X === localAlpha1X) {
      console.log('');
      console.log('✓ SUCCESS: Verification key updated and verified!');
      console.log('  Proofs generated with local proving key should now verify.');
    } else {
      console.log('');
      console.log('⚠ WARNING: VK may not have been set correctly');
    }
    
  } catch (err) {
    console.log('ERROR:', err.message);
    if (err.data) console.log('Data:', err.data);
  }
  
  console.log('');
  console.log('='.repeat(70));
  console.log('Done!');
  console.log('='.repeat(70));
}

main();
